### ISSUE TITLE
issue 清理计划

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#337]
优先级从高到低。

- [x] #336 `detail.js` 的 `detailPromise` 中判断使用缓存前作一个数据合法性判断，非法数据不使用缓存
- [x] #335 在尝试给出建议的函数中首先将名字切分（例如 `[...character]`），然后在名字不为别名和本名的情况下根据切分的单个字符给出建议，需要修改插件 character 和 overview
- [x] #312 `app.js` 中维持一个全局 object ，根据 message id 和时间戳设置定时函数做删除
- [x] #311 上游已经发版本了，测试一下是否修复了这个问题
- [x] #334 再想想，这个改动还是很大的
- [x] 一斗的突破材料好像加了个新 boss 有空再看看补一下材料名
- [x] #329 有空再看一眼

这周计划至少做完前四个。

**Comment by Mark9804** [comment]
> 一斗的突破材料好像加了个新 boss 有空再看看补一下材料名

[兽境王器 | Honey Impact - Genshin Impact DB and Tools](https://genshin.honeyhunterworld.com/db/item/i_215/?lang=CHS)

一斗出来之前我写一个添加资源的工作流文档，打算研究一下内鬼网的图像素材，尽可能把添加新素材的重复流程自动化，要是能脚本化更好

**Comment by Arondight** [comment]
很遗憾 node-fetch 只是在 github 发版了， npm 中没有发版

**Comment by Mark9804** [comment]
问一下，在今天的更改之后要怎么获取群名

旧版是`const groupName = "group" === type ? msg.group_name : undefined;`，新的我看了一下文档，没看到群名称的属性

**Comment by Arondight** [comment]
> 问一下，在今天的更改之后要怎么获取群名

以前怎么用，现在就怎么用， msg 中的属性没有任何减少和变更，只有新增。

**Comment by Arondight** [comment]
> 新的我看了一下文档

最新的提交 38d1de05480cb83388f90329d2b88caeb7eda469 中完全兼容了旧版本的插件，你拉一下代码，然后就可以直接使用旧版本的插件了，就像下面一样。

```
async function Plugin(Message, bot) {
  const msg = Message.raw_message;        // 聊天消息
  const userID = Message.user_id;         // 聊天发起人的 QQ 号
  const groupID = Message.group_id;       // 群消息的群号
  const type = Message.type;              // group 或者 private
  const name = Message.sender.nickname;   // 聊天发起人的 QQ 昵称
  const sendID = "group" === type ? groupID : userID;
  const message = `Welcome to world, ${name} (${userID}) !`;

  await bot.sendMessage(sendID, message, type, userID);
}

export { Plugin as run };
```

**Comment by Mark9804** [comment]
> 最新的提交 38d1de0 中完全兼容了旧版本的插件

好，谢谢老大哥救我狗命
